
function [grid, flow] =  build_structs()

    grid = struct('nu', [], ...
                  'nx', [], 'ny', [], ...
                  'dx',[], 'dy', [], 'dt', [], ...
                  'ntst', [], ...
                  'xmin', [], 'xmax', [], ...
                  'ymin', [], 'ymax', [], ...
                  'ip', [], 'jp', [], 'im', [], 'jm', [], ... 
                  'atbounds', [] ...
                  );
          
    flow = struct('u', [], 'v', [], ...
                  'tr_u', [], 'tr_v', [], ...
                  'rhsu', [], 'rhsv', [], ...
                  'secrhsu', [], 'secrhsv', [] ... 
                  );
              

end